### PR TITLE
Error localization

### LINKED ISSUE #55: Localization of error messages
### 1. Bug/complaint report

**Description:** Some error messages are coming in english, when finnish language is used.
**Expected behavior:** Finnish error messages for each device.
**Is the problem repeatable:** Yes 1. Select finnish language in the account settings. 2. Try to upload when the device is not connected 3. See the error ( english message for many devices).

**Could or did it cause an incident to the patient?** No

**Screenshots:**

**System information:**
- **Sensotrend Uploader version:** v2.36.3
- **Device used as a data source:** N/A
- **Operation system and version:** Win10
- **Possible other system information:**

### 3. Action/implementation details 
**Action/correction plan:**  
**Target schedule:** 

### 4. Verification (for software changes only)
To be verified by following cases:

1. Verify the working of functionality defined above.

**Verification results:**
- [ ] 1. Pass/Fail (your name, SW version, date)

### PR DESCRIPTION
**Pull request by JaWetter**
## Risk analysis
Instruction: Remove bullets not included to the analysis results._

- [x] Risks of the implementation in this pull request have been analyzed with following results:
- No significant risks. 

## Significance
_Instruction: Remove bullet, which is not the analysis result._

- [x] Analysis, is the software change considered significant (ref. [MDCG 2020-3, chart C](https://drive.google.com/file/d/1QAqBhV-6NzuqXCY20kH5cH0VTGl83Jj0/view?usp=sharing)), has been made with following result: 
- **Not significant change**, can be made to the product certified according MDD.
	- Reasons for the decision - A minor bug fix only

## Security check-up

_Instruction: Check that the OWASP top 10 have been taken into account._

[https://github.com/OWASP/www-project-top-ten/blob/master/index.md](https://github.com/OWASP/www-project-top-ten/blob/master/index.md)
- [x] **1 Injection** - A localization fix only
- [x] **2 Broken Authentication** - A localization fix only
- [x] **3 Sensitive Data Exposure** - A localization fix only
- [x] **4 XML External Entities (XXE)** - A localization fix only
- [x] **5 Broken Access Control** - A localization fix only
- [x] **6 Security Misconfiguration** - A localization fix only
- [x] **7 Cross-Site Scripting XSS** - A localization fix only
- [x] **8 Insecure Deserialization** - A localization fix only
- [x] **9 Using Components with Known Vulnerabilities** - A localization fix only
- [x] **10 Insufficient Logging & Monitoring** - A localization fix only

### CODE REVIEW

**Review by HannuHyttinen — APPROVED** [review]
👏 Hyvältä näyttää! Toiminnallisuutta en testannut.

Ps. Pitäisikö versionumeroa package.json:ssa kasvattaa?

**Review by mrinnetmaki — APPROVED** [review]
👍

**Comment by mrinnetmaki** [comment]
> Ps. Pitäisikö versionumeroa package.json:ssa kasvattaa?

Ei ehkä tarvitse nyt, kun muutos menee deviin. Kasvatetaan, kun menee masteriin. Otan sieltä sitten taas deviin ja käännän versiot.

**Comment by mrinnetmaki** [comment]
Implemented in a PR towards the `main` branch, https://github.com/Sensotrend/sensotrend-uploader/pull/78

**Pull request merged**
